apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snapurl-ingress
  namespace: snapurl
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # To support file uploads or large API requests if needed
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - http:
        paths:
          # Backend API Ingress Rule
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000

          # Backend Redirect Ingress Rule
          - path: /r
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000

          # Frontend Ingress Rule
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
