apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: snapurl
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: IMAGE_BACKEND
          imagePullPolicy: Always
          command: ["npm", "run", "worker"]
          envFrom:
            - configMapRef:
                name: snapurl-config
            - secretRef:
                name: snapurl-secrets
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "25m"
              memory: "128Mi"
